apiVersion: v1
kind: Service
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: my-app
    tier: my-app
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: my-app
  labels:
    app: my-app
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: my-app
        tier: my-app
    spec:
      containers:
        - image: 127.0.0.1:30400/my-app:$BUILD_TAG
          name: my-app
          ports:
            - containerPort: 80
              name: my-app
