apiVersion: v1
kind: Service
metadata:
  name: hello-eric
  labels:
    app: hello-eric
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: hello-eric
    tier: hello-eric
  type: NodePort

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-eric
  labels:
    app: hello-eric
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: hello-eric
        tier: hello-eric
    spec:
      containers:
        - image: 127.0.0.1:30400/hello-eric:$BUILD_TAG
          name: hello-eric
          ports:
            - containerPort: 8080
              name: hello-eric
